name: Choco Pack & Push

on:
  workflow_dispatch:
    inputs:
      package:
        type: choice
        description: Which Choco package to pack and push?
        options:
        - foldersync-desktop
        - golden-cheetah
        - github-copilot-cli
        - go-containerregistry
        - px-proxy
        - token2-companion
      dry_run:
        type: boolean
        description: Dry run (skip publishing)?
        default: false

defaults:
  run:
    shell: pwsh

jobs:
  pack_push_choco:
    runs-on: windows-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Pack, test and publish ${{ github.event.inputs.package }}
        uses: ./.github/actions/pack-test-publish
        with:
          package: ${{ github.event.inputs.package }}
          dry-run: ${{ inputs.dry_run }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          choco-key: ${{ secrets.CHOCO_KEY }}
